version: "3.8"

services:
  backend:
    build: .
    container_name: insurance_backend
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}  # Load from .env file

  frontend:
    build: .
    container_name: insurance_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
